name: Deploy To Cloud

on:
  workflow_dispatch:
    inputs:
      newSha:
        required: false
        type: string

  workflow_call:
    inputs:
      newSha:
        required: false
        type: string
    secrets:
      PROJECT_ID:
        required: true
      UMBRACO_CLOUD_API_KEY:
        required: true

jobs:
  prepareDeployment:
    name: Prepare Deployment to cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.newSha }}

      # switch the gitignore files so cloud does not ignore the build frontend assets
      - name: Prepare Cloud Git Ignore
        run: cp cloud.gitignore .gitignore
        shell: bash

      # zip everything, except what is defined in the 'cloud.zipignore'
      - name: Zip Source Code
        run: zip -r sources.zip . -x@cloud.zipignore
        shell: bash

      - name: Store package for upload
        uses: actions/upload-artifact@v4
        with:
          name: source-artifact
          path: ${{GITHUB.WORKSPACE}}/sources.zip
          retention-days: 1

  callUmbracoApi:
    name: Upload Source And Start Deployment
    runs-on: ubuntu-latest
    needs: prepareDeployment
    outputs:
      runningDeploymentId: ${{ steps.deployment-meta.outputs.deploymentId }}
    steps:
      - uses: actions/checkout@v4

      - name: Get package for upload
        uses: actions/download-artifact@v4
        with:
          name: source-artifact

      # Request to prepare a deployment
      # - sets the commit message to be used in cloud 
      # - supplies you with a deploymentId to be used in the rest of the process
      - name: Create Deployment Meta
        id: deployment-meta
        shell: bash
        run: >
          bash ${{GITHUB.WORKSPACE}}/.github/scripts/create_deployment.sh
          ${{ secrets.PROJECT_ID }} 
          ${{ secrets.UMBRACO_CLOUD_API_KEY }} 
          "Run number ${{github.run_number}}" 
          GITHUB

      # Upload your zipped artifact
      - name: Post Zipped Artifact
        shell: bash
        run: >
          bash ${{GITHUB.WORKSPACE}}/.github/scripts/upload_package.sh 
          ${{ secrets.PROJECT_ID }} 
          ${{ steps.deployment-meta.outputs.deploymentId }} 
          ${{ secrets.UMBRACO_CLOUD_API_KEY }} 
          ${{ GITHUB.WORKSPACE }}/sources.zip

      # Actually request to start the deployment process in cloud
      - name: Request Start Deployment
        shell: bash
        run: >
          bash ${{GITHUB.WORKSPACE}}/.github/scripts/start_deployment.sh 
          ${{ secrets.PROJECT_ID }} 
          ${{ steps.deployment-meta.outputs.deploymentId }} 
          ${{ secrets.UMBRACO_CLOUD_API_KEY }}

  awaitDeploymentFinished:
    name: Await deployment to finish
    runs-on: ubuntu-latest
    needs: callUmbracoApi
    steps:
      - uses: actions/checkout@v4

      # Poll until deployment finishes
      - name: Wait for deployment completed
        shell: bash
        env:
          runningDeploymentId: ${{ needs.callUmbracoApi.outputs.runningDeploymentId }}
        run: >
          bash ${{GITHUB.WORKSPACE}}/.github/scripts/get_deployment_status.sh 
          ${{ secrets.PROJECT_ID }} 
          ${{ env.runningDeploymentId }} 
          ${{ secrets.UMBRACO_CLOUD_API_KEY }}
