parameters:
  - name: artifactId
    type: string
  - name: noBuildAndRestore
    type: string
    default: 'false'
  - name: skipVersionCheck
    type: string
    default: 'false'
  - name: skipPreserveUmbracoCloudJson
    type: string
    default: 'false'
  - name: allowAnyTarget
    type: string
    default: 'false'
  - name: runSchemaExtraction
    type: string
    default: 'true'
  - name: targetEnvironmentAlias
    type: string
    default: $(targetEnvironmentAlias)
    
jobs:
  - job: StartDeployment
    displayName: Start Deployment
    steps:
      # Actually request to start the deployment process in cloud
      - task: Bash@3
        displayName: Request Start Deployment
        name: requestStartDeployment
        env:
          artifactId: ${{ parameters.artifactId }}
          noBuildAndRestore: ${{ parameters.noBuildAndRestore }}
          skipVersionCheck: ${{ parameters.skipVersionCheck }}
          skipPreserveUmbracoCloudJson: ${{ parameters.skipPreserveUmbracoCloudJson }}
          allowAnyTarget: ${{ parameters.allowAnyTarget }}
          runSchemaExtraction: ${{ parameters.runSchemaExtraction }}
        inputs:
          targetType: 'filePath'
          filePath: devops/scripts/start_deployment.sh
          arguments: >
            $(projectId)
            $(umbracoCloudApiKey)
            $artifactId
            ${{ parameters.targetEnvironmentAlias }}
            "Run for $(Build.BuildNumber)"
            $noBuildAndRestore
            $skipVersionCheck
            $skipPreserveUmbracoCloudJson
            $allowAnyTarget
            $runSchemaExtraction
            $(pipelineVendor)

  - job: CheckDeploymentProgress
    displayName: Check Deployment Progress
    dependsOn: [ StartDeployment ]
    variables:
      deploymentId: $[ dependencies.StartDeployment.outputs['requestStartDeployment.deploymentId'] ]
    steps:
      # Poll until deployment finishes 
      - task: Bash@3
        displayName: Wait for deployment completed
        inputs:
          targetType: 'filePath'
          filePath: devops/scripts/get_deployment_status.sh
          arguments: > 
            $(projectId)
            $(umbracoCloudApiKey)
            $(deploymentId)