name: Deploy To Cloud

on:
  workflow_dispatch:
    inputs:
      artifactId:
        required: false
        type: string
      targetEnvironmentAlias:
        description: 'The target environment alias to deploy to'
        required: true
        type: string

  workflow_call:
    inputs:
      artifactId:
        required: false
        type: string
      targetEnvironmentAlias:
        description: 'The target environment alias to deploy to'
        required: true
        type: string
    secrets:
      PROJECT_ID:
        required: true
      UMBRACO_CLOUD_API_KEY:
        required: true

jobs:
  startDeployment:
    name: Start Deployment
    runs-on: ubuntu-latest
    outputs:
      runningDeploymentId: ${{ steps.deployment-meta.outputs.deploymentId }}
    steps:
      - uses: actions/checkout@v4

      - name: Get package for upload
        uses: actions/download-artifact@v4
        with:
            name: source-artifact

      # Request to prepare a deployment
      # - sets the commit message to be used in cloud 
      # - supplies you with a deploymentId to be used to query the deployment process
      - name: Create Deployment Meta
        id: deployment-meta
        shell: pwsh
        run: >
          ${{GITHUB.WORKSPACE}}/.github/powershell/Start-Deployment.ps1 
          -ProjectId ${{ secrets.PROJECT_ID }} 
          -ApiKey ${{ secrets.UMBRACO_CLOUD_API_KEY }} 
          -ArtifactId ${{ inputs.artifactId }}
          -TargetEnvironmentAlias ${{ inputs.targetEnvironmentAlias }}
          -CommitMessage "Run number ${{github.run_number}}" 
          -NoBuildAndRestore $True
          -SkipVersionCheck $False
          -PipelineVendor GITHUB


  awaitDeploymentFinished:
    name: Await deployment to finish
    runs-on: ubuntu-latest
    needs: startDeployment
    steps:
      - uses: actions/checkout@v4

      # Poll until deployment finishes 
      - name: Wait for deployment completed 
        shell: pwsh
        env: 
          runningDeploymentId: ${{ needs.startDeployment.outputs.runningDeploymentId }}
        run: >
          ${{GITHUB.WORKSPACE}}/.github/powershell/Test-DeploymentStatus.ps1 
          -ProjectId ${{ secrets.PROJECT_ID }} 
          -DeploymentId ${{ env.runningDeploymentId }} 
          -ApiKey ${{ secrets.UMBRACO_CLOUD_API_KEY }}
